# YAML
version: '3.7'
services:
  rtsp:
    image: aler9/rtsp-simple-server
    network_mode: host
    volumes: 
      - ./rtsp-config.yml:/mediamtx.yml
  webrtc:
    image: ghcr.io/deepch/rtsptoweb:latest
    network_mode: host
    volumes:
      - ./webrtc-config.json:/config/config.json
    depends_on:
      - rtsp
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx-config.template:/etc/nginx/templates/default.conf.template
    environment:
      - NG_PORT=6632
      - API_PORT=819
      - RTC_PORT=8083
  website:
    image: jordan007/iviti-wa:v104
    network_mode: host
    environment:
      - NGINX_PORT=8001
      - BACKEND_PORT=6632
      - STREAM_PORT=8083
    command: >
      /bin/sh -c
      "envsubst '
      $${NGINX_PORT}
      $${BACKEND_PORT}
      $${STREAM_PORT}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
