# YAML
version: '3.7'
services:
  rtsp:
    image: aler9/rtsp-simple-server
    network_mode: host
    volumes: 
      - ./rtsp-config.yml:/mediamtx.yml
  webrtc:
    image: ghcr.io/deepch/rtsptoweb:latest
    network_mode: host
    volumes:
      - ./webrtc-config.json:/config/config.json
    depends_on:
      - rtsp
  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx-config.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_PORT=6632
      - API_PORT=819
      - RTC_PORT=8083
  website:
    image: jordan007/iviti-wa:v013
    ports:
      - "8001:8001" # 外部露出開放的 port 對應到 docker container 的 port
    networks:
      ivit_net:
        ipv4_address: 172.40.0.4

networks:
  ivit_net:
    name: ivit_net
    ipam:
      config:
        - subnet: 172.40.0.0/24